import Header from '@components/Header'
import './globals.css'
import type { Metadata } from 'next'
import Sidebar from '@components/Sidebar'




export const metadata: Metadata = {
  title: 'Amazon Web Scrapper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex bg-gray-100 h-screen'>
         <Sidebar />
        <main className='p-10 max-w-7xl w-full mx-auto overflow-y-auto'>
        <Header />
        {children}
        </main>
       
      </body>
      
      
    </html>
  )
}
